### ISSUE TITLE
Rename to just `karma-chromiumedge-launcher` on npm

### ISSUE THREAD

**Issue by taymoork2** [ChiragRupani/karma-chromiumedge-launcher#3]
By default this plugin will be added to the plugins array for your karma config as it starts with karma-. If you mess with the plugins array in your karma config you may have to include in manually

Since this is a scoped package, karma doesn't automatically find it if you dont provide a plugins array in the config

A couple legacy repos I work on use the no plugin option and would be much appreciated if this package was no longer scoped and `npm i karma-chromium-edge-launcher` as `karma-edgium-launcher` is no longer being updated

**Comment by ChiragRupani** [comment]
Thanks for showing your interest in this package.  

The finding automatically plugin looks like undocumented feature and it is not working for me with default chrome browser.

Since standard practice now is to publish package as scoped packages, it is published and installed as ```npm i -D @chiragrupani/karma-chromium-edge-launcher```.  There are no plans to publish as unscoped package.

Further it is just adding one line to add plugin:
```require("@chiragrupani/karma-chromium-edge-launcher")```
